version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run nodemon:start
    volumes:
      - .:/usr/app/
    ports:
      - "8080:8080"
  web:
    container_name: web
    build:
      context: .
      dockerfile: ui/ui.Dockerfile
    volumes:
      - .:/usr/app/
    ports:
      - "4200:4200"
