version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: nodemon --exec ./node_modules/.bin/ts-node -- ./index.ts
    volumes:
      - .:/usr/app/
    ports:
      - "8080:8080"
  web:
    container_name: web
    build:
      context: .
      dockerfile: ui/ui.Dockerfile
    volumes:
      - .:/usr/app/
    ports:
      - "4200:4200"
